crops:
  - type: "nether_wart"
    limit: 50

  - type: "beetroot"
    limit: 100

  - type: "carrot"
    limit: 90

  - type: "melon_stem"
    limit: 100

  - type: "potato"
    limit: 90

  - type: "pumpkin_stem"
    limit: 80

  - type: "sweet_berry_bush"
    limit: 150

  - type: "wheat"
    limit: 125

locale: "en_US"