name: PoweredFarm
version: '1.0-SNAPSHOT'
main: dev.lucas.poweredFarm.Main
api-version: '1.20'
bootstrapper: dev.lucas.poweredFarm.PoweredFarmBootstrapper

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true